# Generated by Django 5.0.1 on 2024-03-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0003_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
    ]
