# Generated by Django 5.0.1 on 2024-03-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0006_remove_post_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
