# Generated by Django 5.0.1 on 2024-03-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0007_post_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_name',
        ),
    ]
